// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: docs/proto/v1/memora.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReminderRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OffsetDays    int32                  `protobuf:"varint,1,opt,name=offset_days,json=offsetDays,proto3" json:"offset_days,omitempty"`
	Channels      []string               `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReminderRuleRequest) Reset() {
	*x = ReminderRuleRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReminderRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderRuleRequest) ProtoMessage() {}

func (x *ReminderRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderRuleRequest.ProtoReflect.Descriptor instead.
func (*ReminderRuleRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{0}
}

func (x *ReminderRuleRequest) GetOffsetDays() int32 {
	if x != nil {
		return x.OffsetDays
	}
	return 0
}

func (x *ReminderRuleRequest) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

type CreateImportantDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	PersonName    string                 `protobuf:"bytes,3,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"`
	Relationship  string                 `protobuf:"bytes,4,opt,name=relationship,proto3" json:"relationship,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	EventYear     *int32                 `protobuf:"varint,6,opt,name=event_year,json=eventYear,proto3,oneof" json:"event_year,omitempty"`
	EventMonth    int32                  `protobuf:"varint,7,opt,name=event_month,json=eventMonth,proto3" json:"event_month,omitempty"`
	EventDay      int32                  `protobuf:"varint,8,opt,name=event_day,json=eventDay,proto3" json:"event_day,omitempty"`
	Timezone      string                 `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	ReminderTime  string                 `protobuf:"bytes,10,opt,name=reminder_time,json=reminderTime,proto3" json:"reminder_time,omitempty"`
	ReminderRules []*ReminderRuleRequest `protobuf:"bytes,11,rep,name=reminder_rules,json=reminderRules,proto3" json:"reminder_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImportantDayRequest) Reset() {
	*x = CreateImportantDayRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImportantDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImportantDayRequest) ProtoMessage() {}

func (x *CreateImportantDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImportantDayRequest.ProtoReflect.Descriptor instead.
func (*CreateImportantDayRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{1}
}

func (x *CreateImportantDayRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateImportantDayRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateImportantDayRequest) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *CreateImportantDayRequest) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *CreateImportantDayRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateImportantDayRequest) GetEventYear() int32 {
	if x != nil && x.EventYear != nil {
		return *x.EventYear
	}
	return 0
}

func (x *CreateImportantDayRequest) GetEventMonth() int32 {
	if x != nil {
		return x.EventMonth
	}
	return 0
}

func (x *CreateImportantDayRequest) GetEventDay() int32 {
	if x != nil {
		return x.EventDay
	}
	return 0
}

func (x *CreateImportantDayRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateImportantDayRequest) GetReminderTime() string {
	if x != nil {
		return x.ReminderTime
	}
	return ""
}

func (x *CreateImportantDayRequest) GetReminderRules() []*ReminderRuleRequest {
	if x != nil {
		return x.ReminderRules
	}
	return nil
}

type UpdateImportantDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	PersonName    string                 `protobuf:"bytes,4,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"`
	Relationship  string                 `protobuf:"bytes,5,opt,name=relationship,proto3" json:"relationship,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	EventYear     *int32                 `protobuf:"varint,7,opt,name=event_year,json=eventYear,proto3,oneof" json:"event_year,omitempty"`
	EventMonth    int32                  `protobuf:"varint,8,opt,name=event_month,json=eventMonth,proto3" json:"event_month,omitempty"`
	EventDay      int32                  `protobuf:"varint,9,opt,name=event_day,json=eventDay,proto3" json:"event_day,omitempty"`
	Timezone      string                 `protobuf:"bytes,10,opt,name=timezone,proto3" json:"timezone,omitempty"`
	ReminderTime  string                 `protobuf:"bytes,11,opt,name=reminder_time,json=reminderTime,proto3" json:"reminder_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateImportantDayRequest) Reset() {
	*x = UpdateImportantDayRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateImportantDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateImportantDayRequest) ProtoMessage() {}

func (x *UpdateImportantDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateImportantDayRequest.ProtoReflect.Descriptor instead.
func (*UpdateImportantDayRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateImportantDayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateImportantDayRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateImportantDayRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateImportantDayRequest) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *UpdateImportantDayRequest) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *UpdateImportantDayRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateImportantDayRequest) GetEventYear() int32 {
	if x != nil && x.EventYear != nil {
		return *x.EventYear
	}
	return 0
}

func (x *UpdateImportantDayRequest) GetEventMonth() int32 {
	if x != nil {
		return x.EventMonth
	}
	return 0
}

func (x *UpdateImportantDayRequest) GetEventDay() int32 {
	if x != nil {
		return x.EventDay
	}
	return 0
}

func (x *UpdateImportantDayRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UpdateImportantDayRequest) GetReminderTime() string {
	if x != nil {
		return x.ReminderTime
	}
	return ""
}

type GetImportantDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImportantDayRequest) Reset() {
	*x = GetImportantDayRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImportantDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImportantDayRequest) ProtoMessage() {}

func (x *GetImportantDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImportantDayRequest.ProtoReflect.Descriptor instead.
func (*GetImportantDayRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{3}
}

func (x *GetImportantDayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListImportantDaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImportantDaysRequest) Reset() {
	*x = ListImportantDaysRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImportantDaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportantDaysRequest) ProtoMessage() {}

func (x *ListImportantDaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportantDaysRequest.ProtoReflect.Descriptor instead.
func (*ListImportantDaysRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{4}
}

func (x *ListImportantDaysRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListImportantDaysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListImportantDaysRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpcomingImportantDaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpcomingImportantDaysRequest) Reset() {
	*x = UpcomingImportantDaysRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcomingImportantDaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingImportantDaysRequest) ProtoMessage() {}

func (x *UpcomingImportantDaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingImportantDaysRequest.ProtoReflect.Descriptor instead.
func (*UpcomingImportantDaysRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{5}
}

func (x *UpcomingImportantDaysRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *UpcomingImportantDaysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *UpcomingImportantDaysRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReplaceReminderRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rules         []*ReminderRuleRequest `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceReminderRulesRequest) Reset() {
	*x = ReplaceReminderRulesRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceReminderRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceReminderRulesRequest) ProtoMessage() {}

func (x *ReplaceReminderRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceReminderRulesRequest.ProtoReflect.Descriptor instead.
func (*ReplaceReminderRulesRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{6}
}

func (x *ReplaceReminderRulesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReplaceReminderRulesRequest) GetRules() []*ReminderRuleRequest {
	if x != nil {
		return x.Rules
	}
	return nil
}

type DeleteImportantDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImportantDayRequest) Reset() {
	*x = DeleteImportantDayRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImportantDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImportantDayRequest) ProtoMessage() {}

func (x *DeleteImportantDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImportantDayRequest.ProtoReflect.Descriptor instead.
func (*DeleteImportantDayRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteImportantDayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ImportantDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	PersonName    string                 `protobuf:"bytes,5,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"`
	Relationship  string                 `protobuf:"bytes,6,opt,name=relationship,proto3" json:"relationship,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	EventYear     *int32                 `protobuf:"varint,8,opt,name=event_year,json=eventYear,proto3,oneof" json:"event_year,omitempty"`
	EventMonth    int32                  `protobuf:"varint,9,opt,name=event_month,json=eventMonth,proto3" json:"event_month,omitempty"`
	EventDay      int32                  `protobuf:"varint,10,opt,name=event_day,json=eventDay,proto3" json:"event_day,omitempty"`
	Recurrence    string                 `protobuf:"bytes,11,opt,name=recurrence,proto3" json:"recurrence,omitempty"`
	Timezone      string                 `protobuf:"bytes,12,opt,name=timezone,proto3" json:"timezone,omitempty"`
	ReminderTime  string                 `protobuf:"bytes,13,opt,name=reminder_time,json=reminderTime,proto3" json:"reminder_time,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportantDayResponse) Reset() {
	*x = ImportantDayResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportantDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportantDayResponse) ProtoMessage() {}

func (x *ImportantDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportantDayResponse.ProtoReflect.Descriptor instead.
func (*ImportantDayResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{8}
}

func (x *ImportantDayResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImportantDayResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ImportantDayResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImportantDayResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ImportantDayResponse) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *ImportantDayResponse) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *ImportantDayResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ImportantDayResponse) GetEventYear() int32 {
	if x != nil && x.EventYear != nil {
		return *x.EventYear
	}
	return 0
}

func (x *ImportantDayResponse) GetEventMonth() int32 {
	if x != nil {
		return x.EventMonth
	}
	return 0
}

func (x *ImportantDayResponse) GetEventDay() int32 {
	if x != nil {
		return x.EventDay
	}
	return 0
}

func (x *ImportantDayResponse) GetRecurrence() string {
	if x != nil {
		return x.Recurrence
	}
	return ""
}

func (x *ImportantDayResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ImportantDayResponse) GetReminderTime() string {
	if x != nil {
		return x.ReminderTime
	}
	return ""
}

func (x *ImportantDayResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ImportantDayResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UpcomingImportantDayResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImportantDay   *ImportantDayResponse  `protobuf:"bytes,1,opt,name=important_day,json=importantDay,proto3" json:"important_day,omitempty"`
	OccurrenceDate string                 `protobuf:"bytes,2,opt,name=occurrence_date,json=occurrenceDate,proto3" json:"occurrence_date,omitempty"`
	DaysUntil      int32                  `protobuf:"varint,3,opt,name=days_until,json=daysUntil,proto3" json:"days_until,omitempty"`
	Anniversary    *int32                 `protobuf:"varint,4,opt,name=anniversary,proto3,oneof" json:"anniversary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpcomingImportantDayResponse) Reset() {
	*x = UpcomingImportantDayResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcomingImportantDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingImportantDayResponse) ProtoMessage() {}

func (x *UpcomingImportantDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingImportantDayResponse.ProtoReflect.Descriptor instead.
func (*UpcomingImportantDayResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{9}
}

func (x *UpcomingImportantDayResponse) GetImportantDay() *ImportantDayResponse {
	if x != nil {
		return x.ImportantDay
	}
	return nil
}

func (x *UpcomingImportantDayResponse) GetOccurrenceDate() string {
	if x != nil {
		return x.OccurrenceDate
	}
	return ""
}

func (x *UpcomingImportantDayResponse) GetDaysUntil() int32 {
	if x != nil {
		return x.DaysUntil
	}
	return 0
}

func (x *UpcomingImportantDayResponse) GetAnniversary() int32 {
	if x != nil && x.Anniversary != nil {
		return *x.Anniversary
	}
	return 0
}

type ListImportantDaysResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ImportantDays []*ImportantDayResponse `protobuf:"bytes,1,rep,name=important_days,json=importantDays,proto3" json:"important_days,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImportantDaysResponse) Reset() {
	*x = ListImportantDaysResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImportantDaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportantDaysResponse) ProtoMessage() {}

func (x *ListImportantDaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportantDaysResponse.ProtoReflect.Descriptor instead.
func (*ListImportantDaysResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{10}
}

func (x *ListImportantDaysResponse) GetImportantDays() []*ImportantDayResponse {
	if x != nil {
		return x.ImportantDays
	}
	return nil
}

func (x *ListImportantDaysResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpcomingImportantDaysResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	ImportantDays []*UpcomingImportantDayResponse `protobuf:"bytes,1,rep,name=important_days,json=importantDays,proto3" json:"important_days,omitempty"`
	Total         int32                           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpcomingImportantDaysResponse) Reset() {
	*x = UpcomingImportantDaysResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcomingImportantDaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingImportantDaysResponse) ProtoMessage() {}

func (x *UpcomingImportantDaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingImportantDaysResponse.ProtoReflect.Descriptor instead.
func (*UpcomingImportantDaysResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{11}
}

func (x *UpcomingImportantDaysResponse) GetImportantDays() []*UpcomingImportantDayResponse {
	if x != nil {
		return x.ImportantDays
	}
	return nil
}

func (x *UpcomingImportantDaysResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReminderRuleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImportantDayId string                 `protobuf:"bytes,3,opt,name=important_day_id,json=importantDayId,proto3" json:"important_day_id,omitempty"`
	OffsetDays     int32                  `protobuf:"varint,4,opt,name=offset_days,json=offsetDays,proto3" json:"offset_days,omitempty"`
	Channels       []string               `protobuf:"bytes,5,rep,name=channels,proto3" json:"channels,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReminderRuleResponse) Reset() {
	*x = ReminderRuleResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReminderRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderRuleResponse) ProtoMessage() {}

func (x *ReminderRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderRuleResponse.ProtoReflect.Descriptor instead.
func (*ReminderRuleResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{12}
}

func (x *ReminderRuleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReminderRuleResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReminderRuleResponse) GetImportantDayId() string {
	if x != nil {
		return x.ImportantDayId
	}
	return ""
}

func (x *ReminderRuleResponse) GetOffsetDays() int32 {
	if x != nil {
		return x.OffsetDays
	}
	return 0
}

func (x *ReminderRuleResponse) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ReminderRuleResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReminderRuleResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReminderRulesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Rules         []*ReminderRuleResponse `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReminderRulesResponse) Reset() {
	*x = ReminderRulesResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReminderRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderRulesResponse) ProtoMessage() {}

func (x *ReminderRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderRulesResponse.ProtoReflect.Descriptor instead.
func (*ReminderRulesResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{13}
}

func (x *ReminderRulesResponse) GetRules() []*ReminderRuleResponse {
	if x != nil {
		return x.Rules
	}
	return nil
}

type DeleteImportantDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImportantDayResponse) Reset() {
	*x = DeleteImportantDayResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImportantDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImportantDayResponse) ProtoMessage() {}

func (x *DeleteImportantDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImportantDayResponse.ProtoReflect.Descriptor instead.
func (*DeleteImportantDayResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{14}
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadOnly    bool                   `protobuf:"varint,1,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{15}
}

func (x *ListNotificationsRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

func (x *ListNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNotificationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type MarkNotificationReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationReadRequest) Reset() {
	*x = MarkNotificationReadRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReadRequest) ProtoMessage() {}

func (x *MarkNotificationReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationReadRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{16}
}

func (x *MarkNotificationReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MarkAllNotificationsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsReadRequest) Reset() {
	*x = MarkAllNotificationsReadRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsReadRequest) ProtoMessage() {}

func (x *MarkAllNotificationsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsReadRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{17}
}

type NotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImportantDayId *string                `protobuf:"bytes,3,opt,name=important_day_id,json=importantDayId,proto3,oneof" json:"important_day_id,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Body           string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Data           string                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	ReadAt         *string                `protobuf:"bytes,8,opt,name=read_at,json=readAt,proto3,oneof" json:"read_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{18}
}

func (x *NotificationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationResponse) GetImportantDayId() string {
	if x != nil && x.ImportantDayId != nil {
		return *x.ImportantDayId
	}
	return ""
}

func (x *NotificationResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *NotificationResponse) GetReadAt() string {
	if x != nil && x.ReadAt != nil {
		return *x.ReadAt
	}
	return ""
}

func (x *NotificationResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Notifications []*NotificationResponse `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{19}
}

func (x *ListNotificationsResponse) GetNotifications() []*NotificationResponse {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MarkAllNotificationsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsReadResponse) Reset() {
	*x = MarkAllNotificationsReadResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsReadResponse) ProtoMessage() {}

func (x *MarkAllNotificationsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsReadResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{20}
}

type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterDeviceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterDeviceRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceRequest) Reset() {
	*x = DeleteDeviceRequest{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceRequest) ProtoMessage() {}

func (x *DeleteDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeviceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceTokenResponse) Reset() {
	*x = DeviceTokenResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTokenResponse) ProtoMessage() {}

func (x *DeviceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTokenResponse.ProtoReflect.Descriptor instead.
func (*DeviceTokenResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{23}
}

func (x *DeviceTokenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeviceTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeviceTokenResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceTokenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceTokenResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *DeviceTokenResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DeviceTokenResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DeleteDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceResponse) Reset() {
	*x = DeleteDeviceResponse{}
	mi := &file_docs_proto_v1_memora_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceResponse) ProtoMessage() {}

func (x *DeleteDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_memora_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_memora_proto_rawDescGZIP(), []int{24}
}

var File_docs_proto_v1_memora_proto protoreflect.FileDescriptor

const file_docs_proto_v1_memora_proto_rawDesc = "" +
	"\n" +
	"\x1adocs/proto/v1/memora.proto\x12\agrpc.v1\"R\n" +
	"\x13ReminderRuleRequest\x12\x1f\n" +
	"\voffset_days\x18\x01 \x01(\x05R\n" +
	"offsetDays\x12\x1a\n" +
	"\bchannels\x18\x02 \x03(\tR\bchannels\"\xa3\x03\n" +
	"\x19CreateImportantDayRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vperson_name\x18\x03 \x01(\tR\n" +
	"personName\x12\"\n" +
	"\frelationship\x18\x04 \x01(\tR\frelationship\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\n" +
	"event_year\x18\x06 \x01(\x05H\x00R\teventYear\x88\x01\x01\x12\x1f\n" +
	"\vevent_month\x18\a \x01(\x05R\n" +
	"eventMonth\x12\x1b\n" +
	"\tevent_day\x18\b \x01(\x05R\beventDay\x12\x1a\n" +
	"\btimezone\x18\t \x01(\tR\btimezone\x12#\n" +
	"\rreminder_time\x18\n" +
	" \x01(\tR\freminderTime\x12C\n" +
	"\x0ereminder_rules\x18\v \x03(\v2\x1c.grpc.v1.ReminderRuleRequestR\rreminderRulesB\r\n" +
	"\v_event_year\"\xee\x02\n" +
	"\x19UpdateImportantDayRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\vperson_name\x18\x04 \x01(\tR\n" +
	"personName\x12\"\n" +
	"\frelationship\x18\x05 \x01(\tR\frelationship\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\"\n" +
	"\n" +
	"event_year\x18\a \x01(\x05H\x00R\teventYear\x88\x01\x01\x12\x1f\n" +
	"\vevent_month\x18\b \x01(\x05R\n" +
	"eventMonth\x12\x1b\n" +
	"\tevent_day\x18\t \x01(\x05R\beventDay\x12\x1a\n" +
	"\btimezone\x18\n" +
	" \x01(\tR\btimezone\x12#\n" +
	"\rreminder_time\x18\v \x01(\tR\freminderTimeB\r\n" +
	"\v_event_year\"(\n" +
	"\x16GetImportantDayRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x18ListImportantDaysRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"`\n" +
	"\x1cUpcomingImportantDaysRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"a\n" +
	"\x1bReplaceReminderRulesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x05rules\x18\x02 \x03(\v2\x1c.grpc.v1.ReminderRuleRequestR\x05rules\"+\n" +
	"\x19DeleteImportantDayRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe0\x03\n" +
	"\x14ImportantDayResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1f\n" +
	"\vperson_name\x18\x05 \x01(\tR\n" +
	"personName\x12\"\n" +
	"\frelationship\x18\x06 \x01(\tR\frelationship\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\"\n" +
	"\n" +
	"event_year\x18\b \x01(\x05H\x00R\teventYear\x88\x01\x01\x12\x1f\n" +
	"\vevent_month\x18\t \x01(\x05R\n" +
	"eventMonth\x12\x1b\n" +
	"\tevent_day\x18\n" +
	" \x01(\x05R\beventDay\x12\x1e\n" +
	"\n" +
	"recurrence\x18\v \x01(\tR\n" +
	"recurrence\x12\x1a\n" +
	"\btimezone\x18\f \x01(\tR\btimezone\x12#\n" +
	"\rreminder_time\x18\r \x01(\tR\freminderTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAtB\r\n" +
	"\v_event_year\"\xe1\x01\n" +
	"\x1cUpcomingImportantDayResponse\x12B\n" +
	"\rimportant_day\x18\x01 \x01(\v2\x1d.grpc.v1.ImportantDayResponseR\fimportantDay\x12'\n" +
	"\x0foccurrence_date\x18\x02 \x01(\tR\x0eoccurrenceDate\x12\x1d\n" +
	"\n" +
	"days_until\x18\x03 \x01(\x05R\tdaysUntil\x12%\n" +
	"\vanniversary\x18\x04 \x01(\x05H\x00R\vanniversary\x88\x01\x01B\x0e\n" +
	"\f_anniversary\"w\n" +
	"\x19ListImportantDaysResponse\x12D\n" +
	"\x0eimportant_days\x18\x01 \x03(\v2\x1d.grpc.v1.ImportantDayResponseR\rimportantDays\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x83\x01\n" +
	"\x1dUpcomingImportantDaysResponse\x12L\n" +
	"\x0eimportant_days\x18\x01 \x03(\v2%.grpc.v1.UpcomingImportantDayResponseR\rimportantDays\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe4\x01\n" +
	"\x14ReminderRuleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12(\n" +
	"\x10important_day_id\x18\x03 \x01(\tR\x0eimportantDayId\x12\x1f\n" +
	"\voffset_days\x18\x04 \x01(\x05R\n" +
	"offsetDays\x12\x1a\n" +
	"\bchannels\x18\x05 \x03(\tR\bchannels\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"L\n" +
	"\x15ReminderRulesResponse\x123\n" +
	"\x05rules\x18\x01 \x03(\v2\x1d.grpc.v1.ReminderRuleResponseR\x05rules\"\x1c\n" +
	"\x1aDeleteImportantDayResponse\"i\n" +
	"\x18ListNotificationsRequest\x12\x1f\n" +
	"\vunread_only\x18\x01 \x01(\bR\n" +
	"unreadOnly\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"-\n" +
	"\x1bMarkNotificationReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x1fMarkAllNotificationsReadRequest\"\x9e\x02\n" +
	"\x14NotificationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12-\n" +
	"\x10important_day_id\x18\x03 \x01(\tH\x00R\x0eimportantDayId\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x12\n" +
	"\x04data\x18\a \x01(\tR\x04data\x12\x1c\n" +
	"\aread_at\x18\b \x01(\tH\x01R\x06readAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAtB\x13\n" +
	"\x11_important_day_idB\n" +
	"\n" +
	"\b_read_at\"v\n" +
	"\x19ListNotificationsResponse\x12C\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1d.grpc.v1.NotificationResponseR\rnotifications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\"\n" +
	" MarkAllNotificationsReadResponse\"]\n" +
	"\x15RegisterDeviceRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"%\n" +
	"\x13DeleteDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xda\x01\n" +
	"\x13DeviceTokenResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x16\n" +
	"\x14DeleteDeviceResponse2\xa3\x05\n" +
	"\x13ImportantDayService\x12W\n" +
	"\x12CreateImportantDay\x12\".grpc.v1.CreateImportantDayRequest\x1a\x1d.grpc.v1.ImportantDayResponse\x12Q\n" +
	"\x0fGetImportantDay\x12\x1f.grpc.v1.GetImportantDayRequest\x1a\x1d.grpc.v1.ImportantDayResponse\x12Z\n" +
	"\x11ListImportantDays\x12!.grpc.v1.ListImportantDaysRequest\x1a\".grpc.v1.ListImportantDaysResponse\x12f\n" +
	"\x15UpcomingImportantDays\x12%.grpc.v1.UpcomingImportantDaysRequest\x1a&.grpc.v1.UpcomingImportantDaysResponse\x12W\n" +
	"\x12UpdateImportantDay\x12\".grpc.v1.UpdateImportantDayRequest\x1a\x1d.grpc.v1.ImportantDayResponse\x12d\n" +
	"\x1cReplaceImportantDayReminders\x12$.grpc.v1.ReplaceReminderRulesRequest\x1a\x1e.grpc.v1.ReminderRulesResponse\x12]\n" +
	"\x12DeleteImportantDay\x12\".grpc.v1.DeleteImportantDayRequest\x1a#.grpc.v1.DeleteImportantDayResponse2\xbf\x02\n" +
	"\x13NotificationService\x12Z\n" +
	"\x11ListNotifications\x12!.grpc.v1.ListNotificationsRequest\x1a\".grpc.v1.ListNotificationsResponse\x12[\n" +
	"\x14MarkNotificationRead\x12$.grpc.v1.MarkNotificationReadRequest\x1a\x1d.grpc.v1.NotificationResponse\x12o\n" +
	"\x18MarkAllNotificationsRead\x12(.grpc.v1.MarkAllNotificationsReadRequest\x1a).grpc.v1.MarkAllNotificationsReadResponse2\xac\x01\n" +
	"\rDeviceService\x12N\n" +
	"\x0eRegisterDevice\x12\x1e.grpc.v1.RegisterDeviceRequest\x1a\x1c.grpc.v1.DeviceTokenResponse\x12K\n" +
	"\fDeleteDevice\x12\x1c.grpc.v1.DeleteDeviceRequest\x1a\x1d.grpc.v1.DeleteDeviceResponseB\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_memora_proto_rawDescOnce sync.Once
	file_docs_proto_v1_memora_proto_rawDescData []byte
)

func file_docs_proto_v1_memora_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_memora_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_memora_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_memora_proto_rawDesc), len(file_docs_proto_v1_memora_proto_rawDesc)))
	})
	return file_docs_proto_v1_memora_proto_rawDescData
}

var file_docs_proto_v1_memora_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_docs_proto_v1_memora_proto_goTypes = []any{
	(*ReminderRuleRequest)(nil),              // 0: grpc.v1.ReminderRuleRequest
	(*CreateImportantDayRequest)(nil),        // 1: grpc.v1.CreateImportantDayRequest
	(*UpdateImportantDayRequest)(nil),        // 2: grpc.v1.UpdateImportantDayRequest
	(*GetImportantDayRequest)(nil),           // 3: grpc.v1.GetImportantDayRequest
	(*ListImportantDaysRequest)(nil),         // 4: grpc.v1.ListImportantDaysRequest
	(*UpcomingImportantDaysRequest)(nil),     // 5: grpc.v1.UpcomingImportantDaysRequest
	(*ReplaceReminderRulesRequest)(nil),      // 6: grpc.v1.ReplaceReminderRulesRequest
	(*DeleteImportantDayRequest)(nil),        // 7: grpc.v1.DeleteImportantDayRequest
	(*ImportantDayResponse)(nil),             // 8: grpc.v1.ImportantDayResponse
	(*UpcomingImportantDayResponse)(nil),     // 9: grpc.v1.UpcomingImportantDayResponse
	(*ListImportantDaysResponse)(nil),        // 10: grpc.v1.ListImportantDaysResponse
	(*UpcomingImportantDaysResponse)(nil),    // 11: grpc.v1.UpcomingImportantDaysResponse
	(*ReminderRuleResponse)(nil),             // 12: grpc.v1.ReminderRuleResponse
	(*ReminderRulesResponse)(nil),            // 13: grpc.v1.ReminderRulesResponse
	(*DeleteImportantDayResponse)(nil),       // 14: grpc.v1.DeleteImportantDayResponse
	(*ListNotificationsRequest)(nil),         // 15: grpc.v1.ListNotificationsRequest
	(*MarkNotificationReadRequest)(nil),      // 16: grpc.v1.MarkNotificationReadRequest
	(*MarkAllNotificationsReadRequest)(nil),  // 17: grpc.v1.MarkAllNotificationsReadRequest
	(*NotificationResponse)(nil),             // 18: grpc.v1.NotificationResponse
	(*ListNotificationsResponse)(nil),        // 19: grpc.v1.ListNotificationsResponse
	(*MarkAllNotificationsReadResponse)(nil), // 20: grpc.v1.MarkAllNotificationsReadResponse
	(*RegisterDeviceRequest)(nil),            // 21: grpc.v1.RegisterDeviceRequest
	(*DeleteDeviceRequest)(nil),              // 22: grpc.v1.DeleteDeviceRequest
	(*DeviceTokenResponse)(nil),              // 23: grpc.v1.DeviceTokenResponse
	(*DeleteDeviceResponse)(nil),             // 24: grpc.v1.DeleteDeviceResponse
}
var file_docs_proto_v1_memora_proto_depIdxs = []int32{
	0,  // 0: grpc.v1.CreateImportantDayRequest.reminder_rules:type_name -> grpc.v1.ReminderRuleRequest
	0,  // 1: grpc.v1.ReplaceReminderRulesRequest.rules:type_name -> grpc.v1.ReminderRuleRequest
	8,  // 2: grpc.v1.UpcomingImportantDayResponse.important_day:type_name -> grpc.v1.ImportantDayResponse
	8,  // 3: grpc.v1.ListImportantDaysResponse.important_days:type_name -> grpc.v1.ImportantDayResponse
	9,  // 4: grpc.v1.UpcomingImportantDaysResponse.important_days:type_name -> grpc.v1.UpcomingImportantDayResponse
	12, // 5: grpc.v1.ReminderRulesResponse.rules:type_name -> grpc.v1.ReminderRuleResponse
	18, // 6: grpc.v1.ListNotificationsResponse.notifications:type_name -> grpc.v1.NotificationResponse
	1,  // 7: grpc.v1.ImportantDayService.CreateImportantDay:input_type -> grpc.v1.CreateImportantDayRequest
	3,  // 8: grpc.v1.ImportantDayService.GetImportantDay:input_type -> grpc.v1.GetImportantDayRequest
	4,  // 9: grpc.v1.ImportantDayService.ListImportantDays:input_type -> grpc.v1.ListImportantDaysRequest
	5,  // 10: grpc.v1.ImportantDayService.UpcomingImportantDays:input_type -> grpc.v1.UpcomingImportantDaysRequest
	2,  // 11: grpc.v1.ImportantDayService.UpdateImportantDay:input_type -> grpc.v1.UpdateImportantDayRequest
	6,  // 12: grpc.v1.ImportantDayService.ReplaceImportantDayReminders:input_type -> grpc.v1.ReplaceReminderRulesRequest
	7,  // 13: grpc.v1.ImportantDayService.DeleteImportantDay:input_type -> grpc.v1.DeleteImportantDayRequest
	15, // 14: grpc.v1.NotificationService.ListNotifications:input_type -> grpc.v1.ListNotificationsRequest
	16, // 15: grpc.v1.NotificationService.MarkNotificationRead:input_type -> grpc.v1.MarkNotificationReadRequest
	17, // 16: grpc.v1.NotificationService.MarkAllNotificationsRead:input_type -> grpc.v1.MarkAllNotificationsReadRequest
	21, // 17: grpc.v1.DeviceService.RegisterDevice:input_type -> grpc.v1.RegisterDeviceRequest
	22, // 18: grpc.v1.DeviceService.DeleteDevice:input_type -> grpc.v1.DeleteDeviceRequest
	8,  // 19: grpc.v1.ImportantDayService.CreateImportantDay:output_type -> grpc.v1.ImportantDayResponse
	8,  // 20: grpc.v1.ImportantDayService.GetImportantDay:output_type -> grpc.v1.ImportantDayResponse
	10, // 21: grpc.v1.ImportantDayService.ListImportantDays:output_type -> grpc.v1.ListImportantDaysResponse
	11, // 22: grpc.v1.ImportantDayService.UpcomingImportantDays:output_type -> grpc.v1.UpcomingImportantDaysResponse
	8,  // 23: grpc.v1.ImportantDayService.UpdateImportantDay:output_type -> grpc.v1.ImportantDayResponse
	13, // 24: grpc.v1.ImportantDayService.ReplaceImportantDayReminders:output_type -> grpc.v1.ReminderRulesResponse
	14, // 25: grpc.v1.ImportantDayService.DeleteImportantDay:output_type -> grpc.v1.DeleteImportantDayResponse
	19, // 26: grpc.v1.NotificationService.ListNotifications:output_type -> grpc.v1.ListNotificationsResponse
	18, // 27: grpc.v1.NotificationService.MarkNotificationRead:output_type -> grpc.v1.NotificationResponse
	20, // 28: grpc.v1.NotificationService.MarkAllNotificationsRead:output_type -> grpc.v1.MarkAllNotificationsReadResponse
	23, // 29: grpc.v1.DeviceService.RegisterDevice:output_type -> grpc.v1.DeviceTokenResponse
	24, // 30: grpc.v1.DeviceService.DeleteDevice:output_type -> grpc.v1.DeleteDeviceResponse
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_memora_proto_init() }
func file_docs_proto_v1_memora_proto_init() {
	if File_docs_proto_v1_memora_proto != nil {
		return
	}
	file_docs_proto_v1_memora_proto_msgTypes[1].OneofWrappers = []any{}
	file_docs_proto_v1_memora_proto_msgTypes[2].OneofWrappers = []any{}
	file_docs_proto_v1_memora_proto_msgTypes[8].OneofWrappers = []any{}
	file_docs_proto_v1_memora_proto_msgTypes[9].OneofWrappers = []any{}
	file_docs_proto_v1_memora_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_memora_proto_rawDesc), len(file_docs_proto_v1_memora_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_docs_proto_v1_memora_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_memora_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_memora_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_memora_proto = out.File
	file_docs_proto_v1_memora_proto_goTypes = nil
	file_docs_proto_v1_memora_proto_depIdxs = nil
}
