// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: docs/proto/v1/memora.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImportantDayService_CreateImportantDay_FullMethodName           = "/grpc.v1.ImportantDayService/CreateImportantDay"
	ImportantDayService_GetImportantDay_FullMethodName              = "/grpc.v1.ImportantDayService/GetImportantDay"
	ImportantDayService_ListImportantDays_FullMethodName            = "/grpc.v1.ImportantDayService/ListImportantDays"
	ImportantDayService_UpcomingImportantDays_FullMethodName        = "/grpc.v1.ImportantDayService/UpcomingImportantDays"
	ImportantDayService_UpdateImportantDay_FullMethodName           = "/grpc.v1.ImportantDayService/UpdateImportantDay"
	ImportantDayService_ReplaceImportantDayReminders_FullMethodName = "/grpc.v1.ImportantDayService/ReplaceImportantDayReminders"
	ImportantDayService_DeleteImportantDay_FullMethodName           = "/grpc.v1.ImportantDayService/DeleteImportantDay"
)

// ImportantDayServiceClient is the client API for ImportantDayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImportantDayServiceClient interface {
	CreateImportantDay(ctx context.Context, in *CreateImportantDayRequest, opts ...grpc.CallOption) (*ImportantDayResponse, error)
	GetImportantDay(ctx context.Context, in *GetImportantDayRequest, opts ...grpc.CallOption) (*ImportantDayResponse, error)
	ListImportantDays(ctx context.Context, in *ListImportantDaysRequest, opts ...grpc.CallOption) (*ListImportantDaysResponse, error)
	UpcomingImportantDays(ctx context.Context, in *UpcomingImportantDaysRequest, opts ...grpc.CallOption) (*UpcomingImportantDaysResponse, error)
	UpdateImportantDay(ctx context.Context, in *UpdateImportantDayRequest, opts ...grpc.CallOption) (*ImportantDayResponse, error)
	ReplaceImportantDayReminders(ctx context.Context, in *ReplaceReminderRulesRequest, opts ...grpc.CallOption) (*ReminderRulesResponse, error)
	DeleteImportantDay(ctx context.Context, in *DeleteImportantDayRequest, opts ...grpc.CallOption) (*DeleteImportantDayResponse, error)
}

type importantDayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImportantDayServiceClient(cc grpc.ClientConnInterface) ImportantDayServiceClient {
	return &importantDayServiceClient{cc}
}

func (c *importantDayServiceClient) CreateImportantDay(ctx context.Context, in *CreateImportantDayRequest, opts ...grpc.CallOption) (*ImportantDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportantDayResponse)
	err := c.cc.Invoke(ctx, ImportantDayService_CreateImportantDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importantDayServiceClient) GetImportantDay(ctx context.Context, in *GetImportantDayRequest, opts ...grpc.CallOption) (*ImportantDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportantDayResponse)
	err := c.cc.Invoke(ctx, ImportantDayService_GetImportantDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importantDayServiceClient) ListImportantDays(ctx context.Context, in *ListImportantDaysRequest, opts ...grpc.CallOption) (*ListImportantDaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImportantDaysResponse)
	err := c.cc.Invoke(ctx, ImportantDayService_ListImportantDays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importantDayServiceClient) UpcomingImportantDays(ctx context.Context, in *UpcomingImportantDaysRequest, opts ...grpc.CallOption) (*UpcomingImportantDaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpcomingImportantDaysResponse)
	err := c.cc.Invoke(ctx, ImportantDayService_UpcomingImportantDays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importantDayServiceClient) UpdateImportantDay(ctx context.Context, in *UpdateImportantDayRequest, opts ...grpc.CallOption) (*ImportantDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportantDayResponse)
	err := c.cc.Invoke(ctx, ImportantDayService_UpdateImportantDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importantDayServiceClient) ReplaceImportantDayReminders(ctx context.Context, in *ReplaceReminderRulesRequest, opts ...grpc.CallOption) (*ReminderRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReminderRulesResponse)
	err := c.cc.Invoke(ctx, ImportantDayService_ReplaceImportantDayReminders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importantDayServiceClient) DeleteImportantDay(ctx context.Context, in *DeleteImportantDayRequest, opts ...grpc.CallOption) (*DeleteImportantDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteImportantDayResponse)
	err := c.cc.Invoke(ctx, ImportantDayService_DeleteImportantDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImportantDayServiceServer is the server API for ImportantDayService service.
// All implementations must embed UnimplementedImportantDayServiceServer
// for forward compatibility.
type ImportantDayServiceServer interface {
	CreateImportantDay(context.Context, *CreateImportantDayRequest) (*ImportantDayResponse, error)
	GetImportantDay(context.Context, *GetImportantDayRequest) (*ImportantDayResponse, error)
	ListImportantDays(context.Context, *ListImportantDaysRequest) (*ListImportantDaysResponse, error)
	UpcomingImportantDays(context.Context, *UpcomingImportantDaysRequest) (*UpcomingImportantDaysResponse, error)
	UpdateImportantDay(context.Context, *UpdateImportantDayRequest) (*ImportantDayResponse, error)
	ReplaceImportantDayReminders(context.Context, *ReplaceReminderRulesRequest) (*ReminderRulesResponse, error)
	DeleteImportantDay(context.Context, *DeleteImportantDayRequest) (*DeleteImportantDayResponse, error)
	mustEmbedUnimplementedImportantDayServiceServer()
}

// UnimplementedImportantDayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImportantDayServiceServer struct{}

func (UnimplementedImportantDayServiceServer) CreateImportantDay(context.Context, *CreateImportantDayRequest) (*ImportantDayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateImportantDay not implemented")
}
func (UnimplementedImportantDayServiceServer) GetImportantDay(context.Context, *GetImportantDayRequest) (*ImportantDayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImportantDay not implemented")
}
func (UnimplementedImportantDayServiceServer) ListImportantDays(context.Context, *ListImportantDaysRequest) (*ListImportantDaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImportantDays not implemented")
}
func (UnimplementedImportantDayServiceServer) UpcomingImportantDays(context.Context, *UpcomingImportantDaysRequest) (*UpcomingImportantDaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpcomingImportantDays not implemented")
}
func (UnimplementedImportantDayServiceServer) UpdateImportantDay(context.Context, *UpdateImportantDayRequest) (*ImportantDayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateImportantDay not implemented")
}
func (UnimplementedImportantDayServiceServer) ReplaceImportantDayReminders(context.Context, *ReplaceReminderRulesRequest) (*ReminderRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceImportantDayReminders not implemented")
}
func (UnimplementedImportantDayServiceServer) DeleteImportantDay(context.Context, *DeleteImportantDayRequest) (*DeleteImportantDayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteImportantDay not implemented")
}
func (UnimplementedImportantDayServiceServer) mustEmbedUnimplementedImportantDayServiceServer() {}
func (UnimplementedImportantDayServiceServer) testEmbeddedByValue()                             {}

// UnsafeImportantDayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImportantDayServiceServer will
// result in compilation errors.
type UnsafeImportantDayServiceServer interface {
	mustEmbedUnimplementedImportantDayServiceServer()
}

func RegisterImportantDayServiceServer(s grpc.ServiceRegistrar, srv ImportantDayServiceServer) {
	// If the following call panics, it indicates UnimplementedImportantDayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImportantDayService_ServiceDesc, srv)
}

func _ImportantDayService_CreateImportantDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateImportantDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportantDayServiceServer).CreateImportantDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportantDayService_CreateImportantDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportantDayServiceServer).CreateImportantDay(ctx, req.(*CreateImportantDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportantDayService_GetImportantDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImportantDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportantDayServiceServer).GetImportantDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportantDayService_GetImportantDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportantDayServiceServer).GetImportantDay(ctx, req.(*GetImportantDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportantDayService_ListImportantDays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImportantDaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportantDayServiceServer).ListImportantDays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportantDayService_ListImportantDays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportantDayServiceServer).ListImportantDays(ctx, req.(*ListImportantDaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportantDayService_UpcomingImportantDays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpcomingImportantDaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportantDayServiceServer).UpcomingImportantDays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportantDayService_UpcomingImportantDays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportantDayServiceServer).UpcomingImportantDays(ctx, req.(*UpcomingImportantDaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportantDayService_UpdateImportantDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateImportantDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportantDayServiceServer).UpdateImportantDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportantDayService_UpdateImportantDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportantDayServiceServer).UpdateImportantDay(ctx, req.(*UpdateImportantDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportantDayService_ReplaceImportantDayReminders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceReminderRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportantDayServiceServer).ReplaceImportantDayReminders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportantDayService_ReplaceImportantDayReminders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportantDayServiceServer).ReplaceImportantDayReminders(ctx, req.(*ReplaceReminderRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportantDayService_DeleteImportantDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImportantDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportantDayServiceServer).DeleteImportantDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportantDayService_DeleteImportantDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportantDayServiceServer).DeleteImportantDay(ctx, req.(*DeleteImportantDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImportantDayService_ServiceDesc is the grpc.ServiceDesc for ImportantDayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImportantDayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.v1.ImportantDayService",
	HandlerType: (*ImportantDayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateImportantDay",
			Handler:    _ImportantDayService_CreateImportantDay_Handler,
		},
		{
			MethodName: "GetImportantDay",
			Handler:    _ImportantDayService_GetImportantDay_Handler,
		},
		{
			MethodName: "ListImportantDays",
			Handler:    _ImportantDayService_ListImportantDays_Handler,
		},
		{
			MethodName: "UpcomingImportantDays",
			Handler:    _ImportantDayService_UpcomingImportantDays_Handler,
		},
		{
			MethodName: "UpdateImportantDay",
			Handler:    _ImportantDayService_UpdateImportantDay_Handler,
		},
		{
			MethodName: "ReplaceImportantDayReminders",
			Handler:    _ImportantDayService_ReplaceImportantDayReminders_Handler,
		},
		{
			MethodName: "DeleteImportantDay",
			Handler:    _ImportantDayService_DeleteImportantDay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docs/proto/v1/memora.proto",
}

const (
	NotificationService_ListNotifications_FullMethodName        = "/grpc.v1.NotificationService/ListNotifications"
	NotificationService_MarkNotificationRead_FullMethodName     = "/grpc.v1.NotificationService/MarkNotificationRead"
	NotificationService_MarkAllNotificationsRead_FullMethodName = "/grpc.v1.NotificationService/MarkAllNotificationsRead"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error)
	MarkNotificationRead(ctx context.Context, in *MarkNotificationReadRequest, opts ...grpc.CallOption) (*NotificationResponse, error)
	MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReadRequest, opts ...grpc.CallOption) (*MarkAllNotificationsReadResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotificationsResponse)
	err := c.cc.Invoke(ctx, NotificationService_ListNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkNotificationRead(ctx context.Context, in *MarkNotificationReadRequest, opts ...grpc.CallOption) (*NotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, NotificationService_MarkNotificationRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReadRequest, opts ...grpc.CallOption) (*MarkAllNotificationsReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAllNotificationsReadResponse)
	err := c.cc.Invoke(ctx, NotificationService_MarkAllNotificationsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error)
	MarkNotificationRead(context.Context, *MarkNotificationReadRequest) (*NotificationResponse, error)
	MarkAllNotificationsRead(context.Context, *MarkAllNotificationsReadRequest) (*MarkAllNotificationsReadResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) MarkNotificationRead(context.Context, *MarkNotificationReadRequest) (*NotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNotificationRead not implemented")
}
func (UnimplementedNotificationServiceServer) MarkAllNotificationsRead(context.Context, *MarkAllNotificationsReadRequest) (*MarkAllNotificationsReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllNotificationsRead not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListNotifications(ctx, req.(*ListNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkNotificationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkNotificationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MarkNotificationRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkNotificationRead(ctx, req.(*MarkNotificationReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkAllNotificationsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllNotificationsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkAllNotificationsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MarkAllNotificationsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkAllNotificationsRead(ctx, req.(*MarkAllNotificationsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.v1.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNotifications",
			Handler:    _NotificationService_ListNotifications_Handler,
		},
		{
			MethodName: "MarkNotificationRead",
			Handler:    _NotificationService_MarkNotificationRead_Handler,
		},
		{
			MethodName: "MarkAllNotificationsRead",
			Handler:    _NotificationService_MarkAllNotificationsRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docs/proto/v1/memora.proto",
}

const (
	DeviceService_RegisterDevice_FullMethodName = "/grpc.v1.DeviceService/RegisterDevice"
	DeviceService_DeleteDevice_FullMethodName   = "/grpc.v1.DeviceService/DeleteDevice"
)

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceServiceClient interface {
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*DeviceTokenResponse, error)
	DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*DeviceTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceTokenResponse)
	err := c.cc.Invoke(ctx, DeviceService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceService_DeleteDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
// All implementations must embed UnimplementedDeviceServiceServer
// for forward compatibility.
type DeviceServiceServer interface {
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*DeviceTokenResponse, error)
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error)
	mustEmbedUnimplementedDeviceServiceServer()
}

// UnimplementedDeviceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceServiceServer struct{}

func (UnimplementedDeviceServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*DeviceTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedDeviceServiceServer) DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (UnimplementedDeviceServiceServer) mustEmbedUnimplementedDeviceServiceServer() {}
func (UnimplementedDeviceServiceServer) testEmbeddedByValue()                       {}

// UnsafeDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServiceServer will
// result in compilation errors.
type UnsafeDeviceServiceServer interface {
	mustEmbedUnimplementedDeviceServiceServer()
}

func RegisterDeviceServiceServer(s grpc.ServiceRegistrar, srv DeviceServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceService_ServiceDesc, srv)
}

func _DeviceService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_DeleteDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).DeleteDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceService_ServiceDesc is the grpc.ServiceDesc for DeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.v1.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _DeviceService_RegisterDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _DeviceService_DeleteDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docs/proto/v1/memora.proto",
}
