// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user and get access and refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "operationId": "login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.AuthTokens"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Revoke a refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "operationId": "logout",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RefreshToken"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Rotate refresh token and issue a new access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh token",
                "operationId": "refresh-token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RefreshToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.AuthTokens"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register",
                "operationId": "register",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.Register"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/devices": {
            "get": {
                "description": "List active Expo push tokens for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "List devices",
                "operationId": "list-devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.DeviceTokenList"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "post": {
                "description": "Register or reactivate an Expo push token for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Register device",
                "operationId": "register-device",
                "parameters": [
                    {
                        "description": "Device token data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RegisterDevice"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.DeviceToken"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/devices/{id}": {
            "delete": {
                "description": "Deactivate a registered device token by ID",
                "tags": [
                    "devices"
                ],
                "summary": "Delete device",
                "operationId": "delete-device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device token ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/devices/{id}/test-push": {
            "post": {
                "description": "Send a test Expo push notification to a registered device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Send test push",
                "operationId": "test-push",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device token ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Test push copy",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/v1.TestPush"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.PushTestResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/important-days": {
            "get": {
                "description": "List important days for the current user with optional type filtering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "important-days"
                ],
                "summary": "List important days",
                "operationId": "list-important-days",
                "parameters": [
                    {
                        "enum": [
                            "birthday",
                            "wedding",
                            "memorial",
                            "graduation",
                            "first_day",
                            "document",
                            "subscription",
                            "medical",
                            "custom"
                        ],
                        "type": "string",
                        "description": "Filter by important day type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ImportantDayList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "post": {
                "description": "Create an important day and its reminder rules for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "important-days"
                ],
                "summary": "Create important day",
                "operationId": "create-important-day",
                "parameters": [
                    {
                        "description": "Important day data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateImportantDay"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.ImportantDay"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/important-days/upcoming": {
            "get": {
                "description": "List upcoming occurrences for the current user's important days",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "important-days"
                ],
                "summary": "List upcoming important days",
                "operationId": "upcoming-important-days",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 365,
                        "description": "Lookahead window in days",
                        "name": "days",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.UpcomingImportantDayList"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/important-days/{id}": {
            "get": {
                "description": "Get an important day by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "important-days"
                ],
                "summary": "Get important day",
                "operationId": "get-important-day",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Important day ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.ImportantDay"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "put": {
                "description": "Update an important day by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "important-days"
                ],
                "summary": "Update important day",
                "operationId": "update-important-day",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Important day ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Important day data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateImportantDay"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.ImportantDay"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "delete": {
                "description": "Delete an important day by ID",
                "tags": [
                    "important-days"
                ],
                "summary": "Delete important day",
                "operationId": "delete-important-day",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Important day ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/important-days/{id}/reminders": {
            "get": {
                "description": "Get reminder rules for an important day",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "important-days"
                ],
                "summary": "Get important day reminders",
                "operationId": "get-important-day-reminders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Important day ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ReminderRuleList"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "put": {
                "description": "Replace reminder rules for an important day",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "important-days"
                ],
                "summary": "Replace important day reminders",
                "operationId": "replace-important-day-reminders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Important day ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reminder rules",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ReplaceReminderRules"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ReminderRuleList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/mobile/bootstrap": {
            "get": {
                "description": "Get initial data needed by the mobile app after login",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile"
                ],
                "summary": "Get mobile bootstrap",
                "operationId": "mobile-bootstrap",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 30,
                        "description": "Upcoming lookahead window in days",
                        "name": "upcoming_days",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "Upcoming important days limit",
                        "name": "upcoming_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Upcoming important days offset",
                        "name": "upcoming_offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.MobileBootstrap"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/notifications": {
            "get": {
                "description": "List in-app notifications for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List notifications",
                "operationId": "list-notifications",
                "parameters": [
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Only unread notifications",
                        "name": "unread_only",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.NotificationList"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/notifications/read-all": {
            "patch": {
                "description": "Mark all notifications for the current user as read",
                "tags": [
                    "notifications"
                ],
                "summary": "Mark all notifications read",
                "operationId": "mark-all-notifications-read",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/notifications/unread-count": {
            "get": {
                "description": "Get unread in-app notification count for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Count unread notifications",
                "operationId": "count-unread-notifications",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.UnreadNotificationCount"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/notifications/{id}/read": {
            "patch": {
                "description": "Mark one notification as read",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Mark notification read",
                "operationId": "mark-notification-read",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Notification"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/user/profile": {
            "get": {
                "description": "Get current user profile",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get profile",
                "operationId": "profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/user/settings": {
            "get": {
                "description": "Get reminder defaults and notification preferences for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user settings",
                "operationId": "get-user-settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.UserSettings"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "put": {
                "description": "Update reminder defaults and notification preferences for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update user settings",
                "operationId": "update-user-settings",
                "parameters": [
                    {
                        "description": "User settings",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateUserSettings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.UserSettings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        }
    },
    "definitions": {
        "entity.AuthTokens": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                },
                "expires_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "C-Kt0pA3..."
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                }
            }
        },
        "entity.DeviceToken": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Pixel 8"
                },
                "platform": {
                    "type": "string",
                    "example": "android"
                },
                "token": {
                    "type": "string",
                    "example": "ExpoPushToken[xxxxxxxxxxxxxxxxxxxxxx]"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "entity.ImportantDay": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Buy flowers"
                },
                "event_day": {
                    "type": "integer",
                    "example": 13
                },
                "event_month": {
                    "type": "integer",
                    "example": 5
                },
                "event_year": {
                    "type": "integer",
                    "example": 1970
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "person_name": {
                    "type": "string",
                    "example": "Mom"
                },
                "recurrence": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.Recurrence"
                        }
                    ],
                    "example": "yearly"
                },
                "relationship": {
                    "type": "string",
                    "example": "mother"
                },
                "reminder_time": {
                    "type": "string",
                    "example": "09:00"
                },
                "timezone": {
                    "type": "string",
                    "example": "Asia/Jakarta"
                },
                "title": {
                    "type": "string",
                    "example": "Mom birthday"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.ImportantDayType"
                        }
                    ],
                    "example": "birthday"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "entity.ImportantDayType": {
            "type": "string",
            "enum": [
                "birthday",
                "wedding",
                "memorial",
                "graduation",
                "first_day",
                "document",
                "subscription",
                "medical",
                "custom"
            ],
            "x-enum-varnames": [
                "ImportantDayTypeBirthday",
                "ImportantDayTypeWedding",
                "ImportantDayTypeMemorial",
                "ImportantDayTypeGraduation",
                "ImportantDayTypeFirstDay",
                "ImportantDayTypeDocument",
                "ImportantDayTypeSubscription",
                "ImportantDayTypeMedical",
                "ImportantDayTypeCustom"
            ]
        },
        "entity.ImportantDayUpcoming": {
            "type": "object",
            "properties": {
                "anniversary": {
                    "type": "integer",
                    "example": 56
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "days_until": {
                    "type": "integer",
                    "example": 7
                },
                "description": {
                    "type": "string",
                    "example": "Buy flowers"
                },
                "event_day": {
                    "type": "integer",
                    "example": 13
                },
                "event_month": {
                    "type": "integer",
                    "example": 5
                },
                "event_year": {
                    "type": "integer",
                    "example": 1970
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "occurrence_date": {
                    "type": "string",
                    "example": "2026-05-13"
                },
                "person_name": {
                    "type": "string",
                    "example": "Mom"
                },
                "recurrence": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.Recurrence"
                        }
                    ],
                    "example": "yearly"
                },
                "relationship": {
                    "type": "string",
                    "example": "mother"
                },
                "reminder_time": {
                    "type": "string",
                    "example": "09:00"
                },
                "timezone": {
                    "type": "string",
                    "example": "Asia/Jakarta"
                },
                "title": {
                    "type": "string",
                    "example": "Mom birthday"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.ImportantDayType"
                        }
                    ],
                    "example": "birthday"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "entity.Notification": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "Mom birthday is in 7 days."
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "data": {
                    "type": "string",
                    "example": "{}"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "important_day_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "read_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "example": "Mom birthday is coming"
                },
                "type": {
                    "type": "string",
                    "example": "reminder"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "entity.PushTestResult": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "sent_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "ticket_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                }
            }
        },
        "entity.Recurrence": {
            "type": "string",
            "enum": [
                "yearly"
            ],
            "x-enum-varnames": [
                "RecurrenceYearly"
            ]
        },
        "entity.ReminderChannel": {
            "type": "string",
            "enum": [
                "email",
                "in_app",
                "push"
            ],
            "x-enum-varnames": [
                "ReminderChannelEmail",
                "ReminderChannelInApp",
                "ReminderChannelPush"
            ]
        },
        "entity.ReminderRule": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ReminderChannel"
                    },
                    "example": [
                        "email"
                    ]
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "important_day_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "offset_days": {
                    "type": "integer",
                    "example": 7
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "entity.UserSettings": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "notification_channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ReminderChannel"
                    },
                    "example": [
                        "email"
                    ]
                },
                "reminder_time": {
                    "type": "string",
                    "example": "09:00"
                },
                "timezone": {
                    "type": "string",
                    "example": "Asia/Jakarta"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "v1.CreateImportantDay": {
            "type": "object",
            "required": [
                "event_day",
                "event_month",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Buy flowers"
                },
                "event_day": {
                    "type": "integer",
                    "maximum": 31,
                    "minimum": 1,
                    "example": 13
                },
                "event_month": {
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1,
                    "example": 5
                },
                "event_year": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1970
                },
                "person_name": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "Mom"
                },
                "relationship": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "mother"
                },
                "reminder_rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ReminderRuleRequest"
                    }
                },
                "reminder_time": {
                    "type": "string",
                    "example": "09:00"
                },
                "timezone": {
                    "type": "string",
                    "maxLength": 64,
                    "example": "Asia/Jakarta"
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "Mom birthday"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "birthday",
                        "wedding",
                        "memorial",
                        "graduation",
                        "first_day",
                        "document",
                        "subscription",
                        "medical",
                        "custom"
                    ],
                    "example": "birthday"
                }
            }
        },
        "v1.DeviceTokenList": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.DeviceToken"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "v1.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "validation_error"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "validation failed"
                }
            }
        },
        "v1.ImportantDayList": {
            "type": "object",
            "properties": {
                "important_days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ImportantDay"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "v1.Login": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "example": "secret123"
                }
            }
        },
        "v1.MobileBootstrap": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.DeviceToken"
                    }
                },
                "devices_total": {
                    "type": "integer",
                    "example": 1
                },
                "settings": {
                    "$ref": "#/definitions/entity.UserSettings"
                },
                "unread_notification_count": {
                    "type": "integer",
                    "example": 2
                },
                "upcoming_important_days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ImportantDayUpcoming"
                    }
                },
                "upcoming_total": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "v1.NotificationList": {
            "type": "object",
            "properties": {
                "notifications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Notification"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "v1.RefreshToken": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "C-Kt0pA3..."
                }
            }
        },
        "v1.Register": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8,
                    "example": "secret123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3,
                    "example": "johndoe"
                }
            }
        },
        "v1.RegisterDevice": {
            "type": "object",
            "required": [
                "platform",
                "token"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "Pixel 8"
                },
                "platform": {
                    "type": "string",
                    "maxLength": 40,
                    "example": "android"
                },
                "token": {
                    "type": "string",
                    "example": "ExpoPushToken[xxxxxxxxxxxxxxxxxxxxxx]"
                }
            }
        },
        "v1.ReminderRuleList": {
            "type": "object",
            "properties": {
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ReminderRule"
                    }
                }
            }
        },
        "v1.ReminderRuleRequest": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ReminderChannel"
                    }
                },
                "offset_days": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 7
                }
            }
        },
        "v1.ReplaceReminderRules": {
            "type": "object",
            "properties": {
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ReminderRuleRequest"
                    }
                }
            }
        },
        "v1.TestPush": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "Push notifications are working."
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "Memora test"
                }
            }
        },
        "v1.UnreadNotificationCount": {
            "type": "object",
            "properties": {
                "unread_count": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "v1.UpcomingImportantDayList": {
            "type": "object",
            "properties": {
                "important_days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ImportantDayUpcoming"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "v1.UpdateImportantDay": {
            "type": "object",
            "required": [
                "event_day",
                "event_month",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Buy flowers"
                },
                "event_day": {
                    "type": "integer",
                    "maximum": 31,
                    "minimum": 1,
                    "example": 13
                },
                "event_month": {
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1,
                    "example": 5
                },
                "event_year": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1970
                },
                "person_name": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "Mom"
                },
                "relationship": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "mother"
                },
                "reminder_time": {
                    "type": "string",
                    "example": "09:00"
                },
                "timezone": {
                    "type": "string",
                    "maxLength": 64,
                    "example": "Asia/Jakarta"
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "Mom birthday"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "birthday",
                        "wedding",
                        "memorial",
                        "graduation",
                        "first_day",
                        "document",
                        "subscription",
                        "medical",
                        "custom"
                    ],
                    "example": "birthday"
                }
            }
        },
        "v1.UpdateUserSettings": {
            "type": "object",
            "properties": {
                "notification_channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ReminderChannel"
                    },
                    "example": [
                        "email"
                    ]
                },
                "reminder_time": {
                    "type": "string",
                    "example": "09:00"
                },
                "timezone": {
                    "type": "string",
                    "maxLength": 64,
                    "example": "Asia/Jakarta"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Memora API",
	Description:      "Backend API for Memora important days, reminders, notifications, devices, and auth",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
